# mkdocs.yml
site_name: YoungIn Mobility Support
site_url: https://ynu09.github.io/YMO-support/
theme:
  name: material
  language: ko

nav:
  - 홈: index.md
  - Go2:
      - 모델 소개: go2/model.md
      - 납품 교육 - 조종기/앱: go2/education.md 
      - 개발 가이드: go2/develop_manual.md
      - Q&A:
        - 하드웨어: go2/Q&A/hardware.md
        - 앱: go2/Q&A/app.md
        - 개발: go2/Q&A/develop.md
  - G1:
      - 모델 소개: g1/model.md
      - 납품 교육 - 조종기/앱: g1/education.md 
      - 개발 가이드: g1/develop_manual.md
      - Q&A:
        - 하드웨어: g1/Q&A/hardware.md
        - 앱: g1/Q&A/app.md
        - 개발: g1/Q&A/develop.md
  - Inspire:
      - DFX- Ultimate C: inspire/dfx.md
      - DFTP - Ultimate D: inspire/dftp.md
  - Z1:
      - 모델 소개: z1/model.md
      - 하드웨어: z1/hardware.md
      - 개발 가이드: z1/develop_manual.md

  - A/S: after_service/after_service.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ynu09/YMO-support

  meta:
    - name: "google-site-verification"
      content: "GpGrsmshxREolDgxoIzlkTJUDyK7jCoHiDW71qhI-mA"
    - name: description
      content: 영인모빌리티 Unitree 로봇 기술지원 페이지입니다. Go2, G1, Z1, Inspire 시리즈의 사용 가이드 및 개발 문서를 제공합니다.
    - name: keywords
      content: 영인모빌리티, YoungIn, youngin, youginmobility, 로봇, Go2, go2, G1, g1, Z1, z1, R1, r1, ROS2, Unitree, unitree
    - name: author
      content: 서연우

