# mkdocs.yml
site_name: YoungIn Mobility Support
site_url: https://ynu09.github.io/YMO-support/
theme:
  name: material
  language: ko

nav:
  - 홈: index.md
  - Go2:
      - 모델 소개: go2/model.md
      - 하드웨어: go2/hardware.md
      - 앱: go2/app.md
      - 개발: go2/develop.md
  - G1:
      - 하드웨어: g1/hardware.md